# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

# Load the CSV file into a DataFrame
file_path = "Electronic_sales_Sep2023-Sep2024.csv"  # Replace with your CSV file path
data = pd.read_csv(file_path)

# Display the first few rows to understand the structure
print("Data Preview:")
print(data.head())

import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

column_name = 'Total Price'

# Calculate Mean, Median, and Mode
mean = data[column_name].mean()
median = data[column_name].median()
mode = data[column_name].mode()[0]

# Calculate Variance, Standard Deviation, and Range
variance = np.var(data[column_name], ddof=1)
std_dev = np.std(data[column_name], ddof=1)
range = max(data[column_name]) - min(data[column_name])



# Print results
print("Measure of Central Tendency:")
print(f"Mean: {mean}")
print(f"Median: {median}")
print(f"Mode: {mode}")

print("Measure of Dispersion:")
print(f"Variance: {variance}")
print(f"Standard Deviation: {std_dev}")
print(f"Range: {range}")

plt.hist(data[column_name], bins=8, color='blue', alpha=0.7, edgecolor='black')
plt.title("Histogram of Total Price")
plt.xlabel("Value")
plt.ylabel("Frequency")
plt.show()

plt.boxplot(data[column_name], vert=False)
plt.title("Box Plot of Total Price")
plt.xlabel("Value")
plt.show()

